### ISSUE TITLE
Erratic PointCloudMap

### ISSUE THREAD

**Issue by Pithone** [roelkok/Kinect-VFX-Graph#1]
In Unity 2018.3, HDRP, the scene Basic arranges the point in these flat XY planes
![basic inspector](https://user-images.githubusercontent.com/49025042/55328925-c85a6500-548d-11e9-9d21-4c36d8138078.PNG)

While the scene Basic Mapped displays this map, that has a correct volume but is erratic
 ![UqTRid12xF](https://user-images.githubusercontent.com/49025042/55328742-626ddd80-548d-11e9-912e-9351ea3e553b.gif)

**Comment by roelkok** [comment]
This seems an issue with the compute shader. I published a new version (v1.1.0) which explicitly finds the kernels by their name. Perhaps that will solve this issue.

**Comment by roelkok** [comment]
Alright I have been able to reproduce this bug by using the integrated graphics from my laptop (Intel HD Graphics 630).

**Comment by Pithone** [comment]
That's sounds to me like a good reason for this issue.
Hard to check if it's a Unity bug or an intel GPU driver one.
I incline towards the Unity side, as i'm experiencing an almost identical issue on the PointCloud with Keijiro repo for RealSense + VFX.
![rsvfx issue](https://user-images.githubusercontent.com/49025042/55463291-ff00be80-55f8-11e9-81b6-8a6bc8f77834.gif)

**Comment by roelkok** [comment]
Seemed to be shader compatability issues. Applied fixes in 69d3c494bd10033a4272fadac82b445953c345b9
