### ISSUE TITLE
Kinect Color Map only Black and White?

### ISSUE THREAD

**Issue by ibilab** [roelkok/Kinect-VFX-Graph#2]
Hi, I'm trying to get the Kinect Color Map to actually have colors (like in your sample GIF), but it's only black and white, I thought it was a postFX thing but it doesn't solve the issue. 

Any parameter I should look into?
I've tried all I could in the Kinect VFX panel (Use color, swapping color maps etc)
Thanks!

Edit: Using Unity 2018.3.10f1

**Comment by ibilab** [comment]
It's working fine after a Unity reboot ;)
Edit: (I spoke too fast...)

**Comment by ibilab** [comment]
Mmmm, actually what I saw was only a fixed texture render (like a fixed screencap from the Colormap, not updating, weird). So it looks like I can't get any color infos in the KinectColorMap, even if changing RGB parameters or others. I'm pretty sure I'm missing something. I will try 2018.3.7f1 tomorrow to check if it's Unity related. Any help would be great.

Note: My Kinect V2 is working properly, tested in Depthkit and Touchdesigner.

**Comment by roelkok** [comment]
Just tried the Blocks scene in 2018.3.7f1, checked the 'Use Color' checkbox and for me it works. During development I did have some issues with the texture not updating, but that was typically resolved by restarting Unity.

**Comment by ibilab** [comment]
Ok, I'll try that. Thanks for sharing

**Comment by ibilab** [comment]
Ok, I'll try that. Thanks for sharing
